version: '3'
services:
  citus:
    image: citusdata/citus:12.1
    container_name: citus
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypass
  app:
    image: "oven/bun"
    # override default entrypoint allows us to do `bun install` before serving
    entrypoint: []
    # execute bun install before we start the dev server in watch mode
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    # expose the right ports
    ports: ["3000:3000"]
    # setup a host mounted volume to sync changes to the container
    volumes: ["./:/home/bun/app"]